name: Check changes and previous PR job status

on:
  workflow_call:
    outputs:
      new_commits:
        description: "Check if new commits was pushed"
        value: ${{ jobs.check.outputs.new_commits }}


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v4
      - name: Get latest workflow info
        id: latest-workflow
        env:
          CURRENT_BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          function get_last_workflow() {
            # get all previus workflows for "test_full.yml" file and current branch
            _workflows=$(curl -H "Accept: application/vnd.github.v3+json" "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/workflows/tests_full.yml/runs?branch=$CURRENT_BRANCH")
            # clear unsupported characters
            _workflows_safe=$(echo "$_workflows" | tr "\r" " " | tr "\n" " " | tr "\t" " ")
            # select previous (current is with index 0) workflow
            _last_workflow=$(echo "$_workflows_safe" | jq -c '.workflow_runs[1]')
            echo "$_last_workflow"
          }
          # get last workflow
          workflow=$(get_last_workflow)
          # wait (max is 60min) if the last workflow is still running
          max_time=$((SECONDS+60*60))
          while [[ "$workflow" != "null" && "$(echo $workflow | jq -r '.status')" != "completed" && $SECONDS -lt $max_time ]];
          do
            workflow=$(get_last_workflow)
            echo "Waiting for workflow + $(echo $workflow | jq -r '.id')"
            sleep 20
          done
          # define an empty value if the workflow is not found
          if [[ -z "$workflow" ]]; then
            workflow='{"head_sha": "", "status": "", "conclusion": ""}'
          fi
          echo "::set-output name=workflow::$workflow"
      - name: Check to see if there is any new commit
        id: new-commit
        env:
          LATEST_HEAD_SHA: ${{ fromJson(steps.latest-workflow.outputs.workflow).head_sha }}
          CURRENT_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          if [ "$LATEST_HEAD_SHA" != "$CURRENT_SHA" ]
          then
            echo "::set-output name=new::1"
            echo "There's a new commit."
          else
            echo "::set-output name=new::0"
            echo "There is no new commit."
          fi
