name: Functional tests

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        description: "Python version"
        type: string
        default: "3.10"
      tox-version:
        required: false
        description: "Tox version, which should be used, e.g. `<4`"
        type: string
        default: ""
      working-directory:
        required: false
        description: "To change working directory"
        type: string
        default: "."
      snapcraft:
        required: false
        description: "Flag if snap is tested."
        type: boolean
        default: false
      posargs:
        required: false
        description: |
          "Optional postargs for `tox -e func -- <postargs>`, e.g. '--series jammy'"
        type: string
        default: "['']"  # empty string as default so func test is run at least one
      # actions-operator
      juju-env:
        required: false
        type: boolean
        default: false
      provider:
        required: false
        type: string
        default: "lxd"

jobs:
  func:
    name: Functional tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: true
      matrix:
        posargs: ${{ fromJson(inputs.posargs) }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "tox${{ inputs.tox-version }}"
      - name: Setup Juju environment
        if: ${{ inputs.juju-env }}
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: ${{ inputs.provider }}
      - name: Remove tox install by actions-operator
        if: ${{ inputs.juju-env }}
        run: sudo apt remove tox -y
      - name: Install snapcraft
        if: ${{ inputs.snapcraft }}
        run: sudo snap install snapcraft --classic
      - name: Run tests with `${{ matrix.posargs }}` posargs
        working-directory: ${{ inputs.working-directory }}
        run: tox -e func -- -sv ${{ matrix.posargs }}
