name: Functional tests

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        description: "Python version"
        type: string
        default: "3.10"
      tox-version:
        required: false
        description: "Tox version, which should be used, e.g. `<4`"
        type: string
        default: ""
      working-directory:
        required: false
        description: "To change working directory"
        type: string
        default: "."
      snapcraft:
        required: false
        description: "Flag if snap is tested."
        type: boolean
        default: false
      commands:
        required: false
        description: |
          Command to run functional test in strategies. It defaults to
          `make functional`, but is defined as a list, so `['make functional']`.
          This allows you to run multiple tests with different parameters.
          Examples:
          - ['FUNC_ARGS="--series jammy" make functional',
             'FUNC_ARGS="--series focal" make functional']
          - ['tox -e func -- -sv --series jammy', 'tox -e func -- -sv --series focal']
        type: string
        default: "['make functional']"
      # actions-operator
      provider:
        required: false
        type: string
        default: "lxd"
      nested-containers:
        required: false
        type: boolean
        default: false

jobs:
  func:
    name: Functional tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: true
      matrix:
        command: ${{ fromJson(inputs.commands) }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install "tox${{ inputs.tox-version }}"
      - name: Setup Juju environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: ${{ inputs.provider }}
      - name: Enabled nested LXD containers
        if: ${{ inputs.provider == 'lxd' && inputs.nested-containers }}
        run: |
          lxc profile set default security.nesting=true
          lxc profile set default security.privileged=true
      - name: Remove tox install by actions-operator
        run: sudo apt remove tox -y
      - name: Install snapcraft
        if: ${{ inputs.snapcraft }}
        run: sudo snap install snapcraft --classic
      - name: Run tests with `${{ matrix.command }}`
        working-directory: ${{ inputs.working-directory }}
        run: ${{ matrix.command }}
