name: BootStack GitHub repos configuration

on:
  workflow_dispatch:
    inputs:
      github-token:
        description: "Your personal GitHub Token to trigger configuration"
        type: string
        required: true

jobs:
  configure-all-repos:
    name: Sync repository settings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Load config file for repo configuration
        id: load_config
        shell: bash
        run: |
          echo "content<<EOF"        >> $GITHUB_OUTPUT
          cat ./repos/settings.yaml  >> $GITHUB_OUTPUT
          echo "EOF"                 >> $GITHUB_OUTPUT
      - uses: txqueuelen/reposettings@v1
        with:
          github_token: ${{ inputs.github-token }}
          config: |
            ${{ steps.load_config.outputs.content }}
